
LIBRARY ieee;
LIBRARY work;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all;
USE ieee.std_logic_arith.all;
USE work.hcc_package.all;
USE work.hcc_library_package.all;

--**********************************************
--***                                        ***
--*** Generated by Floating Point Compiler   ***
--***                                        ***
--*** Copyright Altera Corporation 2010      ***
--***                                        ***
--***                                        ***
--*** Version 10R2 - December 1, 2010        ***
--***                                        ***
--***                                        ***
--**********************************************

ENTITY altfp_matrix_add6_fpc1a IS
PORT (
      sysclk : IN STD_LOGIC;
      reset : IN STD_LOGIC;
      enable : IN STD_LOGIC;
      startin : IN STD_LOGIC;
      one : IN STD_LOGIC_VECTOR (32 DOWNTO 1);
      two : IN STD_LOGIC_VECTOR (32 DOWNTO 1);
      three : IN STD_LOGIC_VECTOR (32 DOWNTO 1);
      four : IN STD_LOGIC_VECTOR (32 DOWNTO 1);
      five : IN STD_LOGIC_VECTOR (32 DOWNTO 1);
      six : IN STD_LOGIC_VECTOR (32 DOWNTO 1);

      startout : OUT STD_LOGIC;
      result : OUT STD_LOGIC_VECTOR (32 DOWNTO 1)
     );
END altfp_matrix_add6_fpc1a;

ARCHITECTURE gen OF altfp_matrix_add6_fpc1a IS

  signal synth0000 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0001 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0002 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0003 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0004 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0005 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0006 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0007 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0008 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0009 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0010 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0011 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0012 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0013 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0014 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0015 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0016 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0017 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0018 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0019 : STD_LOGIC_VECTOR (49 DOWNTO 1);

  signal startff : STD_LOGIC_VECTOR (24 DOWNTO 1);

BEGIN

  psd: PROCESS (sysclk,reset)
  BEGIN
    IF (reset = '1') THEN
      FOR k IN 1 TO 24 LOOP
        startff(k) <= '0';
      END LOOP;
    ELSIF (rising_edge(sysclk)) THEN
      IF (enable = '1') THEN
        startff(1) <= startin;
        FOR k IN 2 TO 24 LOOP
          startff(k) <= startff(k-1);
        END LOOP;
      END IF;
    END IF;
  END PROCESS;

  synth0000 <= one;
  synth0001 <= two;
  synth0002 <= three;
  synth0003 <= four;
  synth0004 <= five;
  synth0005 <= six;

  result <= synth0018;

  cmp0: hcc_alufp1x
  GENERIC MAP (mantissa=>36,shiftspeed=>1,outputpipe=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            addsub=>'0',
            aa=>synth0016(46 DOWNTO 1),
            aasat=>synth0016(47),aazip=>synth0016(48),aanan=>synth0016(49),
            bb=>synth0017(46 DOWNTO 1),
            bbsat=>synth0017(47),bbzip=>synth0017(48),bbnan=>synth0017(49),
            cc=>synth0007(46 DOWNTO 1),
            ccsat=>synth0007(47),cczip=>synth0007(48),ccnan=>synth0007(49));

  cmp1: hcc_alufp1x
  GENERIC MAP (mantissa=>36,shiftspeed=>1,outputpipe=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            addsub=>'0',
            aa=>synth0014(46 DOWNTO 1),
            aasat=>synth0014(47),aazip=>synth0014(48),aanan=>synth0014(49),
            bb=>synth0015(46 DOWNTO 1),
            bbsat=>synth0015(47),bbzip=>synth0015(48),bbnan=>synth0015(49),
            cc=>synth0008(46 DOWNTO 1),
            ccsat=>synth0008(47),cczip=>synth0008(48),ccnan=>synth0008(49));

  cmp2: hcc_alufp1x
  GENERIC MAP (mantissa=>36,shiftspeed=>1,outputpipe=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            addsub=>'0',
            aa=>synth0012(46 DOWNTO 1),
            aasat=>synth0012(47),aazip=>synth0012(48),aanan=>synth0012(49),
            bb=>synth0013(46 DOWNTO 1),
            bbsat=>synth0013(47),bbzip=>synth0013(48),bbnan=>synth0013(49),
            cc=>synth0009(46 DOWNTO 1),
            ccsat=>synth0009(47),cczip=>synth0009(48),ccnan=>synth0009(49));

  cmp3: hcc_alufp1x
  GENERIC MAP (mantissa=>36,shiftspeed=>1,outputpipe=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            addsub=>'0',
            aa=>synth0009(46 DOWNTO 1),
            aasat=>synth0009(47),aazip=>synth0009(48),aanan=>synth0009(49),
            bb=>synth0008(46 DOWNTO 1),
            bbsat=>synth0008(47),bbzip=>synth0008(48),bbnan=>synth0008(49),
            cc=>synth0010(46 DOWNTO 1),
            ccsat=>synth0010(47),cczip=>synth0010(48),ccnan=>synth0010(49));

  cmp4: hcc_alufp1x
  GENERIC MAP (mantissa=>36,shiftspeed=>1,outputpipe=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            addsub=>'0',
            aa=>synth0010(46 DOWNTO 1),
            aasat=>synth0010(47),aazip=>synth0010(48),aanan=>synth0010(49),
            bb=>synth0019(46 DOWNTO 1),
            bbsat=>synth0019(47),bbzip=>synth0019(48),bbnan=>synth0019(49),
            cc=>synth0011(46 DOWNTO 1),
            ccsat=>synth0011(47),cczip=>synth0011(48),ccnan=>synth0011(49));

  cmp5: hcc_castftox
  GENERIC MAP (target=>0,roundconvert=>0,mantissa=>36,outputpipe=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            aa=>synth0000(32 DOWNTO 1),
            cc=>synth0012(46 DOWNTO 1),
            ccsat=>synth0012(47),cczip=>synth0012(48),ccnan=>synth0012(49));

  cmp6: hcc_castftox
  GENERIC MAP (target=>0,roundconvert=>0,mantissa=>36,outputpipe=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            aa=>synth0001(32 DOWNTO 1),
            cc=>synth0013(46 DOWNTO 1),
            ccsat=>synth0013(47),cczip=>synth0013(48),ccnan=>synth0013(49));

  cmp7: hcc_castftox
  GENERIC MAP (target=>0,roundconvert=>0,mantissa=>36,outputpipe=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            aa=>synth0002(32 DOWNTO 1),
            cc=>synth0014(46 DOWNTO 1),
            ccsat=>synth0014(47),cczip=>synth0014(48),ccnan=>synth0014(49));

  cmp8: hcc_castftox
  GENERIC MAP (target=>0,roundconvert=>0,mantissa=>36,outputpipe=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            aa=>synth0003(32 DOWNTO 1),
            cc=>synth0015(46 DOWNTO 1),
            ccsat=>synth0015(47),cczip=>synth0015(48),ccnan=>synth0015(49));

  cmp9: hcc_castftox
  GENERIC MAP (target=>0,roundconvert=>0,mantissa=>36,outputpipe=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            aa=>synth0004(32 DOWNTO 1),
            cc=>synth0016(46 DOWNTO 1),
            ccsat=>synth0016(47),cczip=>synth0016(48),ccnan=>synth0016(49));

  cmp10: hcc_castftox
  GENERIC MAP (target=>0,roundconvert=>0,mantissa=>36,outputpipe=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            aa=>synth0005(32 DOWNTO 1),
            cc=>synth0017(46 DOWNTO 1),
            ccsat=>synth0017(47),cczip=>synth0017(48),ccnan=>synth0017(49));

  cmp11: hcc_castxtof
  GENERIC MAP (mantissa=>36,normspeed=>2)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            aa=>synth0011(46 DOWNTO 1),
            aasat=>synth0011(47),aazip=>synth0011(48),aanan=>synth0011(49),
            cc=>synth0018(32 DOWNTO 1));

  cmp12: hcc_delay
  GENERIC MAP (width=>49,delay=>5,synthesize=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            aa=>synth0007(49 DOWNTO 1),
            cc=>synth0019(49 DOWNTO 1));

  startout <= startff(24);

END GEN;

