
LIBRARY ieee;
LIBRARY work;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all;
USE ieee.std_logic_arith.all;
USE work.hcc_package.all;
USE work.hcc_library_package.all;

--**********************************************
--***                                        ***
--*** Generated by Floating Point Compiler   ***
--***                                        ***
--*** Copyright Altera Corporation 2010      ***
--***                                        ***
--***                                        ***
--*** Version 10R2 - December 1, 2010        ***
--***                                        ***
--***                                        ***
--**********************************************

ENTITY altfp_matrix_vec_fpc2a IS
PORT (
      sysclk : IN STD_LOGIC;
      reset : IN STD_LOGIC;
      enable : IN STD_LOGIC;
      startin : IN STD_LOGIC;
      L000 : IN STD_LOGIC_VECTOR (32 DOWNTO 1);
      L001 : IN STD_LOGIC_VECTOR (32 DOWNTO 1);
      L002 : IN STD_LOGIC_VECTOR (32 DOWNTO 1);
      L003 : IN STD_LOGIC_VECTOR (32 DOWNTO 1);
      L004 : IN STD_LOGIC_VECTOR (32 DOWNTO 1);
      L005 : IN STD_LOGIC_VECTOR (32 DOWNTO 1);
      L006 : IN STD_LOGIC_VECTOR (32 DOWNTO 1);
      L007 : IN STD_LOGIC_VECTOR (32 DOWNTO 1);
      M000 : IN STD_LOGIC_VECTOR (32 DOWNTO 1);
      M001 : IN STD_LOGIC_VECTOR (32 DOWNTO 1);
      M002 : IN STD_LOGIC_VECTOR (32 DOWNTO 1);
      M003 : IN STD_LOGIC_VECTOR (32 DOWNTO 1);
      M004 : IN STD_LOGIC_VECTOR (32 DOWNTO 1);
      M005 : IN STD_LOGIC_VECTOR (32 DOWNTO 1);
      M006 : IN STD_LOGIC_VECTOR (32 DOWNTO 1);
      M007 : IN STD_LOGIC_VECTOR (32 DOWNTO 1);

      startout : OUT STD_LOGIC;
      result : OUT STD_LOGIC_VECTOR (32 DOWNTO 1)
     );
END altfp_matrix_vec_fpc2a;

ARCHITECTURE gen OF altfp_matrix_vec_fpc2a IS

  signal synth0000 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0001 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0002 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0003 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0004 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0005 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0006 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0007 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0008 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0009 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0010 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0011 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0012 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0013 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0014 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0015 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0016 : STD_LOGIC_VECTOR (32 DOWNTO 1);
  signal synth0017 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0018 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0019 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0020 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0021 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0022 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0023 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0024 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0025 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0026 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0027 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0028 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0029 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0030 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0031 : STD_LOGIC_VECTOR (49 DOWNTO 1);
  signal synth0032 : STD_LOGIC_VECTOR (32 DOWNTO 1);

  signal startff : STD_LOGIC_VECTOR (25 DOWNTO 1);

BEGIN

  psd: PROCESS (sysclk,reset)
  BEGIN
    IF (reset = '1') THEN
      FOR k IN 1 TO 25 LOOP
        startff(k) <= '0';
      END LOOP;
    ELSIF (rising_edge(sysclk)) THEN
      IF (enable = '1') THEN
        startff(1) <= startin;
        FOR k IN 2 TO 25 LOOP
          startff(k) <= startff(k-1);
        END LOOP;
      END IF;
    END IF;
  END PROCESS;

  synth0000 <= L000;
  synth0001 <= L001;
  synth0002 <= L002;
  synth0003 <= L003;
  synth0004 <= L004;
  synth0005 <= L005;
  synth0006 <= L006;
  synth0007 <= L007;
  synth0008 <= M000;
  synth0009 <= M001;
  synth0010 <= M002;
  synth0011 <= M003;
  synth0012 <= M004;
  synth0013 <= M005;
  synth0014 <= M006;
  synth0015 <= M007;

  result <= synth0032;

  cmp0: hcc_mulfp1_dot
  GENERIC MAP (mantissa=>36,device=>2,optimization=>2,synthesize=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            aa=>synth0007(32 DOWNTO 1),
            bb=>synth0015(32 DOWNTO 1),
            cc=>synth0017(46 DOWNTO 1),
            ccsat=>synth0017(47),cczip=>synth0017(48),ccnan=>synth0017(49));

  cmp1: hcc_mulfp1_dot
  GENERIC MAP (mantissa=>36,device=>2,optimization=>2,synthesize=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            aa=>synth0006(32 DOWNTO 1),
            bb=>synth0014(32 DOWNTO 1),
            cc=>synth0018(46 DOWNTO 1),
            ccsat=>synth0018(47),cczip=>synth0018(48),ccnan=>synth0018(49));

  cmp2: hcc_mulfp1_dot
  GENERIC MAP (mantissa=>36,device=>2,optimization=>2,synthesize=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            aa=>synth0005(32 DOWNTO 1),
            bb=>synth0013(32 DOWNTO 1),
            cc=>synth0019(46 DOWNTO 1),
            ccsat=>synth0019(47),cczip=>synth0019(48),ccnan=>synth0019(49));

  cmp3: hcc_mulfp1_dot
  GENERIC MAP (mantissa=>36,device=>2,optimization=>2,synthesize=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            aa=>synth0004(32 DOWNTO 1),
            bb=>synth0012(32 DOWNTO 1),
            cc=>synth0020(46 DOWNTO 1),
            ccsat=>synth0020(47),cczip=>synth0020(48),ccnan=>synth0020(49));

  cmp4: hcc_mulfp1_dot
  GENERIC MAP (mantissa=>36,device=>2,optimization=>2,synthesize=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            aa=>synth0003(32 DOWNTO 1),
            bb=>synth0011(32 DOWNTO 1),
            cc=>synth0021(46 DOWNTO 1),
            ccsat=>synth0021(47),cczip=>synth0021(48),ccnan=>synth0021(49));

  cmp5: hcc_mulfp1_dot
  GENERIC MAP (mantissa=>36,device=>2,optimization=>2,synthesize=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            aa=>synth0002(32 DOWNTO 1),
            bb=>synth0010(32 DOWNTO 1),
            cc=>synth0022(46 DOWNTO 1),
            ccsat=>synth0022(47),cczip=>synth0022(48),ccnan=>synth0022(49));

  cmp6: hcc_mulfp1_dot
  GENERIC MAP (mantissa=>36,device=>2,optimization=>2,synthesize=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            aa=>synth0001(32 DOWNTO 1),
            bb=>synth0009(32 DOWNTO 1),
            cc=>synth0023(46 DOWNTO 1),
            ccsat=>synth0023(47),cczip=>synth0023(48),ccnan=>synth0023(49));

  cmp7: hcc_mulfp1_dot
  GENERIC MAP (mantissa=>36,device=>2,optimization=>2,synthesize=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            aa=>synth0000(32 DOWNTO 1),
            bb=>synth0008(32 DOWNTO 1),
            cc=>synth0024(46 DOWNTO 1),
            ccsat=>synth0024(47),cczip=>synth0024(48),ccnan=>synth0024(49));

  cmp8: hcc_alufp1_dot
  GENERIC MAP (mantissa=>36,shiftspeed=>1,outputpipe=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            addsub=>'0',
            aa=>synth0018(46 DOWNTO 1),
            aasat=>synth0018(47),aazip=>synth0018(48),aanan=>synth0018(49),
            bb=>synth0017(46 DOWNTO 1),
            bbsat=>synth0017(47),bbzip=>synth0017(48),bbnan=>synth0017(49),
            cc=>synth0025(46 DOWNTO 1),
            ccsat=>synth0025(47),cczip=>synth0025(48),ccnan=>synth0025(49));

  cmp9: hcc_alufp1_dot
  GENERIC MAP (mantissa=>36,shiftspeed=>1,outputpipe=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            addsub=>'0',
            aa=>synth0020(46 DOWNTO 1),
            aasat=>synth0020(47),aazip=>synth0020(48),aanan=>synth0020(49),
            bb=>synth0019(46 DOWNTO 1),
            bbsat=>synth0019(47),bbzip=>synth0019(48),bbnan=>synth0019(49),
            cc=>synth0026(46 DOWNTO 1),
            ccsat=>synth0026(47),cczip=>synth0026(48),ccnan=>synth0026(49));

  cmp10: hcc_alufp1_dot
  GENERIC MAP (mantissa=>36,shiftspeed=>1,outputpipe=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            addsub=>'0',
            aa=>synth0022(46 DOWNTO 1),
            aasat=>synth0022(47),aazip=>synth0022(48),aanan=>synth0022(49),
            bb=>synth0021(46 DOWNTO 1),
            bbsat=>synth0021(47),bbzip=>synth0021(48),bbnan=>synth0021(49),
            cc=>synth0027(46 DOWNTO 1),
            ccsat=>synth0027(47),cczip=>synth0027(48),ccnan=>synth0027(49));

  cmp11: hcc_alufp1_dot
  GENERIC MAP (mantissa=>36,shiftspeed=>1,outputpipe=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            addsub=>'0',
            aa=>synth0024(46 DOWNTO 1),
            aasat=>synth0024(47),aazip=>synth0024(48),aanan=>synth0024(49),
            bb=>synth0023(46 DOWNTO 1),
            bbsat=>synth0023(47),bbzip=>synth0023(48),bbnan=>synth0023(49),
            cc=>synth0028(46 DOWNTO 1),
            ccsat=>synth0028(47),cczip=>synth0028(48),ccnan=>synth0028(49));

  cmp12: hcc_alufp1x
  GENERIC MAP (mantissa=>36,shiftspeed=>1,outputpipe=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            addsub=>'0',
            aa=>synth0026(46 DOWNTO 1),
            aasat=>synth0026(47),aazip=>synth0026(48),aanan=>synth0026(49),
            bb=>synth0025(46 DOWNTO 1),
            bbsat=>synth0025(47),bbzip=>synth0025(48),bbnan=>synth0025(49),
            cc=>synth0029(46 DOWNTO 1),
            ccsat=>synth0029(47),cczip=>synth0029(48),ccnan=>synth0029(49));

  cmp13: hcc_alufp1x
  GENERIC MAP (mantissa=>36,shiftspeed=>1,outputpipe=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            addsub=>'0',
            aa=>synth0028(46 DOWNTO 1),
            aasat=>synth0028(47),aazip=>synth0028(48),aanan=>synth0028(49),
            bb=>synth0027(46 DOWNTO 1),
            bbsat=>synth0027(47),bbzip=>synth0027(48),bbnan=>synth0027(49),
            cc=>synth0030(46 DOWNTO 1),
            ccsat=>synth0030(47),cczip=>synth0030(48),ccnan=>synth0030(49));

  cmp14: hcc_alufp1x
  GENERIC MAP (mantissa=>36,shiftspeed=>1,outputpipe=>1)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            addsub=>'0',
            aa=>synth0030(46 DOWNTO 1),
            aasat=>synth0030(47),aazip=>synth0030(48),aanan=>synth0030(49),
            bb=>synth0029(46 DOWNTO 1),
            bbsat=>synth0029(47),bbzip=>synth0029(48),bbnan=>synth0029(49),
            cc=>synth0031(46 DOWNTO 1),
            ccsat=>synth0031(47),cczip=>synth0031(48),ccnan=>synth0031(49));

  cmp15: hcc_castxtof
  GENERIC MAP (mantissa=>36,normspeed=>2)
  PORT MAP (sysclk=>sysclk,reset=>reset,enable=>enable,
            aa=>synth0031(46 DOWNTO 1),
            aasat=>synth0031(47),aazip=>synth0031(48),aanan=>synth0031(49),
            cc=>synth0032(32 DOWNTO 1));

  startout <= startff(25);

END GEN;

