// soc_system_mm_interconnect_1.v

// This file was auto-generated from altera_merlin_interconnect_wrapper_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 13.1 162 at 2015.06.22.13:01:49

`timescale 1 ps / 1 ps
module soc_system_mm_interconnect_1 (
		input  wire [11:0]  hps_0_h2f_axi_master_awid,                                        //                                       hps_0_h2f_axi_master.awid
		input  wire [29:0]  hps_0_h2f_axi_master_awaddr,                                      //                                                           .awaddr
		input  wire [3:0]   hps_0_h2f_axi_master_awlen,                                       //                                                           .awlen
		input  wire [2:0]   hps_0_h2f_axi_master_awsize,                                      //                                                           .awsize
		input  wire [1:0]   hps_0_h2f_axi_master_awburst,                                     //                                                           .awburst
		input  wire [1:0]   hps_0_h2f_axi_master_awlock,                                      //                                                           .awlock
		input  wire [3:0]   hps_0_h2f_axi_master_awcache,                                     //                                                           .awcache
		input  wire [2:0]   hps_0_h2f_axi_master_awprot,                                      //                                                           .awprot
		input  wire         hps_0_h2f_axi_master_awvalid,                                     //                                                           .awvalid
		output wire         hps_0_h2f_axi_master_awready,                                     //                                                           .awready
		input  wire [11:0]  hps_0_h2f_axi_master_wid,                                         //                                                           .wid
		input  wire [127:0] hps_0_h2f_axi_master_wdata,                                       //                                                           .wdata
		input  wire [15:0]  hps_0_h2f_axi_master_wstrb,                                       //                                                           .wstrb
		input  wire         hps_0_h2f_axi_master_wlast,                                       //                                                           .wlast
		input  wire         hps_0_h2f_axi_master_wvalid,                                      //                                                           .wvalid
		output wire         hps_0_h2f_axi_master_wready,                                      //                                                           .wready
		output wire [11:0]  hps_0_h2f_axi_master_bid,                                         //                                                           .bid
		output wire [1:0]   hps_0_h2f_axi_master_bresp,                                       //                                                           .bresp
		output wire         hps_0_h2f_axi_master_bvalid,                                      //                                                           .bvalid
		input  wire         hps_0_h2f_axi_master_bready,                                      //                                                           .bready
		input  wire [11:0]  hps_0_h2f_axi_master_arid,                                        //                                                           .arid
		input  wire [29:0]  hps_0_h2f_axi_master_araddr,                                      //                                                           .araddr
		input  wire [3:0]   hps_0_h2f_axi_master_arlen,                                       //                                                           .arlen
		input  wire [2:0]   hps_0_h2f_axi_master_arsize,                                      //                                                           .arsize
		input  wire [1:0]   hps_0_h2f_axi_master_arburst,                                     //                                                           .arburst
		input  wire [1:0]   hps_0_h2f_axi_master_arlock,                                      //                                                           .arlock
		input  wire [3:0]   hps_0_h2f_axi_master_arcache,                                     //                                                           .arcache
		input  wire [2:0]   hps_0_h2f_axi_master_arprot,                                      //                                                           .arprot
		input  wire         hps_0_h2f_axi_master_arvalid,                                     //                                                           .arvalid
		output wire         hps_0_h2f_axi_master_arready,                                     //                                                           .arready
		output wire [11:0]  hps_0_h2f_axi_master_rid,                                         //                                                           .rid
		output wire [127:0] hps_0_h2f_axi_master_rdata,                                       //                                                           .rdata
		output wire [1:0]   hps_0_h2f_axi_master_rresp,                                       //                                                           .rresp
		output wire         hps_0_h2f_axi_master_rlast,                                       //                                                           .rlast
		output wire         hps_0_h2f_axi_master_rvalid,                                      //                                                           .rvalid
		input  wire         hps_0_h2f_axi_master_rready,                                      //                                                           .rready
		input  wire         clock_bridge_0_out_clk_clk,                                       //                                     clock_bridge_0_out_clk.clk
		input  wire         hps_0_h2f_user0_clock_clk,                                        //                                      hps_0_h2f_user0_clock.clk
		input  wire         h2f_slave_0_reset_reset_bridge_in_reset_reset,                    //                    h2f_slave_0_reset_reset_bridge_in_reset.reset
		input  wire         hps_0_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset_reset, // hps_0_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset.reset
		output wire [25:0]  h2f_slave_0_s0_address,                                           //                                             h2f_slave_0_s0.address
		output wire         h2f_slave_0_s0_write,                                             //                                                           .write
		output wire         h2f_slave_0_s0_read,                                              //                                                           .read
		input  wire [127:0] h2f_slave_0_s0_readdata,                                          //                                                           .readdata
		output wire [127:0] h2f_slave_0_s0_writedata,                                         //                                                           .writedata
		output wire [5:0]   h2f_slave_0_s0_burstcount,                                        //                                                           .burstcount
		output wire [15:0]  h2f_slave_0_s0_byteenable,                                        //                                                           .byteenable
		input  wire         h2f_slave_0_s0_readdatavalid,                                     //                                                           .readdatavalid
		input  wire         h2f_slave_0_s0_waitrequest,                                       //                                                           .waitrequest
		output wire         h2f_slave_0_s0_debugaccess                                        //                                                           .debugaccess
	);

	wire          rsp_xbar_mux_src_endofpacket;                                                        // rsp_xbar_mux:src_endofpacket -> hps_0_h2f_axi_master_agent:write_rp_endofpacket
	wire          rsp_xbar_mux_src_valid;                                                              // rsp_xbar_mux:src_valid -> hps_0_h2f_axi_master_agent:write_rp_valid
	wire          rsp_xbar_mux_src_startofpacket;                                                      // rsp_xbar_mux:src_startofpacket -> hps_0_h2f_axi_master_agent:write_rp_startofpacket
	wire  [233:0] rsp_xbar_mux_src_data;                                                               // rsp_xbar_mux:src_data -> hps_0_h2f_axi_master_agent:write_rp_data
	wire    [1:0] rsp_xbar_mux_src_channel;                                                            // rsp_xbar_mux:src_channel -> hps_0_h2f_axi_master_agent:write_rp_channel
	wire          rsp_xbar_mux_src_ready;                                                              // hps_0_h2f_axi_master_agent:write_rp_ready -> rsp_xbar_mux:src_ready
	wire          rsp_xbar_mux_001_src_endofpacket;                                                    // rsp_xbar_mux_001:src_endofpacket -> hps_0_h2f_axi_master_agent:read_rp_endofpacket
	wire          rsp_xbar_mux_001_src_valid;                                                          // rsp_xbar_mux_001:src_valid -> hps_0_h2f_axi_master_agent:read_rp_valid
	wire          rsp_xbar_mux_001_src_startofpacket;                                                  // rsp_xbar_mux_001:src_startofpacket -> hps_0_h2f_axi_master_agent:read_rp_startofpacket
	wire  [233:0] rsp_xbar_mux_001_src_data;                                                           // rsp_xbar_mux_001:src_data -> hps_0_h2f_axi_master_agent:read_rp_data
	wire    [1:0] rsp_xbar_mux_001_src_channel;                                                        // rsp_xbar_mux_001:src_channel -> hps_0_h2f_axi_master_agent:read_rp_channel
	wire          rsp_xbar_mux_001_src_ready;                                                          // hps_0_h2f_axi_master_agent:read_rp_ready -> rsp_xbar_mux_001:src_ready
	wire          h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_waitrequest;             // h2f_slave_0_s0_translator:uav_waitrequest -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:m0_waitrequest
	wire    [9:0] h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_burstcount;              // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:m0_burstcount -> h2f_slave_0_s0_translator:uav_burstcount
	wire  [127:0] h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_writedata;               // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:m0_writedata -> h2f_slave_0_s0_translator:uav_writedata
	wire   [29:0] h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_address;                 // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:m0_address -> h2f_slave_0_s0_translator:uav_address
	wire          h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_write;                   // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:m0_write -> h2f_slave_0_s0_translator:uav_write
	wire          h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_lock;                    // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:m0_lock -> h2f_slave_0_s0_translator:uav_lock
	wire          h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_read;                    // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:m0_read -> h2f_slave_0_s0_translator:uav_read
	wire  [127:0] h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_readdata;                // h2f_slave_0_s0_translator:uav_readdata -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:m0_readdata
	wire          h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_readdatavalid;           // h2f_slave_0_s0_translator:uav_readdatavalid -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:m0_readdatavalid
	wire          h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_debugaccess;             // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:m0_debugaccess -> h2f_slave_0_s0_translator:uav_debugaccess
	wire   [15:0] h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_byteenable;              // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:m0_byteenable -> h2f_slave_0_s0_translator:uav_byteenable
	wire          h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rf_source_endofpacket;      // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:rf_source_endofpacket -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo:in_endofpacket
	wire          h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rf_source_valid;            // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:rf_source_valid -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo:in_valid
	wire          h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rf_source_startofpacket;    // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:rf_source_startofpacket -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo:in_startofpacket
	wire  [234:0] h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rf_source_data;             // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:rf_source_data -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo:in_data
	wire          h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rf_source_ready;            // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo:in_ready -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:rf_source_ready
	wire          h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_endofpacket;   // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo:out_endofpacket -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:rf_sink_endofpacket
	wire          h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_valid;         // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo:out_valid -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:rf_sink_valid
	wire          h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_startofpacket; // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo:out_startofpacket -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:rf_sink_startofpacket
	wire  [234:0] h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_data;          // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo:out_data -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:rf_sink_data
	wire          h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_ready;         // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:rf_sink_ready -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo:out_ready
	wire          h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo_src_valid;       // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:rdata_fifo_src_valid -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo:in_valid
	wire  [129:0] h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo_src_data;        // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:rdata_fifo_src_data -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo:in_data
	wire          h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo_src_ready;       // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo:in_ready -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:rdata_fifo_src_ready
	wire          h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo_out_valid;       // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo:out_valid -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:rdata_fifo_sink_valid
	wire  [129:0] h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo_out_data;        // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo:out_data -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:rdata_fifo_sink_data
	wire          h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo_out_ready;       // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:rdata_fifo_sink_ready -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo:out_ready
	wire          hps_0_h2f_axi_master_agent_write_cp_endofpacket;                                     // hps_0_h2f_axi_master_agent:write_cp_endofpacket -> addr_router:sink_endofpacket
	wire          hps_0_h2f_axi_master_agent_write_cp_valid;                                           // hps_0_h2f_axi_master_agent:write_cp_valid -> addr_router:sink_valid
	wire          hps_0_h2f_axi_master_agent_write_cp_startofpacket;                                   // hps_0_h2f_axi_master_agent:write_cp_startofpacket -> addr_router:sink_startofpacket
	wire  [233:0] hps_0_h2f_axi_master_agent_write_cp_data;                                            // hps_0_h2f_axi_master_agent:write_cp_data -> addr_router:sink_data
	wire          hps_0_h2f_axi_master_agent_write_cp_ready;                                           // addr_router:sink_ready -> hps_0_h2f_axi_master_agent:write_cp_ready
	wire          addr_router_src_endofpacket;                                                         // addr_router:src_endofpacket -> cmd_xbar_demux:sink_endofpacket
	wire          addr_router_src_valid;                                                               // addr_router:src_valid -> cmd_xbar_demux:sink_valid
	wire          addr_router_src_startofpacket;                                                       // addr_router:src_startofpacket -> cmd_xbar_demux:sink_startofpacket
	wire  [233:0] addr_router_src_data;                                                                // addr_router:src_data -> cmd_xbar_demux:sink_data
	wire    [1:0] addr_router_src_channel;                                                             // addr_router:src_channel -> cmd_xbar_demux:sink_channel
	wire          addr_router_src_ready;                                                               // cmd_xbar_demux:sink_ready -> addr_router:src_ready
	wire          hps_0_h2f_axi_master_agent_read_cp_endofpacket;                                      // hps_0_h2f_axi_master_agent:read_cp_endofpacket -> addr_router_001:sink_endofpacket
	wire          hps_0_h2f_axi_master_agent_read_cp_valid;                                            // hps_0_h2f_axi_master_agent:read_cp_valid -> addr_router_001:sink_valid
	wire          hps_0_h2f_axi_master_agent_read_cp_startofpacket;                                    // hps_0_h2f_axi_master_agent:read_cp_startofpacket -> addr_router_001:sink_startofpacket
	wire  [233:0] hps_0_h2f_axi_master_agent_read_cp_data;                                             // hps_0_h2f_axi_master_agent:read_cp_data -> addr_router_001:sink_data
	wire          hps_0_h2f_axi_master_agent_read_cp_ready;                                            // addr_router_001:sink_ready -> hps_0_h2f_axi_master_agent:read_cp_ready
	wire          addr_router_001_src_endofpacket;                                                     // addr_router_001:src_endofpacket -> cmd_xbar_demux_001:sink_endofpacket
	wire          addr_router_001_src_valid;                                                           // addr_router_001:src_valid -> cmd_xbar_demux_001:sink_valid
	wire          addr_router_001_src_startofpacket;                                                   // addr_router_001:src_startofpacket -> cmd_xbar_demux_001:sink_startofpacket
	wire  [233:0] addr_router_001_src_data;                                                            // addr_router_001:src_data -> cmd_xbar_demux_001:sink_data
	wire    [1:0] addr_router_001_src_channel;                                                         // addr_router_001:src_channel -> cmd_xbar_demux_001:sink_channel
	wire          addr_router_001_src_ready;                                                           // cmd_xbar_demux_001:sink_ready -> addr_router_001:src_ready
	wire          h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rp_endofpacket;             // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:rp_endofpacket -> id_router:sink_endofpacket
	wire          h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rp_valid;                   // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:rp_valid -> id_router:sink_valid
	wire          h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rp_startofpacket;           // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:rp_startofpacket -> id_router:sink_startofpacket
	wire  [233:0] h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rp_data;                    // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:rp_data -> id_router:sink_data
	wire          h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rp_ready;                   // id_router:sink_ready -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:rp_ready
	wire          id_router_src_endofpacket;                                                           // id_router:src_endofpacket -> rsp_xbar_demux:sink_endofpacket
	wire          id_router_src_valid;                                                                 // id_router:src_valid -> rsp_xbar_demux:sink_valid
	wire          id_router_src_startofpacket;                                                         // id_router:src_startofpacket -> rsp_xbar_demux:sink_startofpacket
	wire  [233:0] id_router_src_data;                                                                  // id_router:src_data -> rsp_xbar_demux:sink_data
	wire    [1:0] id_router_src_channel;                                                               // id_router:src_channel -> rsp_xbar_demux:sink_channel
	wire          id_router_src_ready;                                                                 // rsp_xbar_demux:sink_ready -> id_router:src_ready
	wire          cmd_xbar_mux_src_endofpacket;                                                        // cmd_xbar_mux:src_endofpacket -> burst_adapter:sink0_endofpacket
	wire          cmd_xbar_mux_src_valid;                                                              // cmd_xbar_mux:src_valid -> burst_adapter:sink0_valid
	wire          cmd_xbar_mux_src_startofpacket;                                                      // cmd_xbar_mux:src_startofpacket -> burst_adapter:sink0_startofpacket
	wire  [233:0] cmd_xbar_mux_src_data;                                                               // cmd_xbar_mux:src_data -> burst_adapter:sink0_data
	wire    [1:0] cmd_xbar_mux_src_channel;                                                            // cmd_xbar_mux:src_channel -> burst_adapter:sink0_channel
	wire          cmd_xbar_mux_src_ready;                                                              // burst_adapter:sink0_ready -> cmd_xbar_mux:src_ready
	wire          burst_adapter_source0_endofpacket;                                                   // burst_adapter:source0_endofpacket -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:cp_endofpacket
	wire          burst_adapter_source0_valid;                                                         // burst_adapter:source0_valid -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:cp_valid
	wire          burst_adapter_source0_startofpacket;                                                 // burst_adapter:source0_startofpacket -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:cp_startofpacket
	wire  [233:0] burst_adapter_source0_data;                                                          // burst_adapter:source0_data -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:cp_data
	wire          burst_adapter_source0_ready;                                                         // h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:cp_ready -> burst_adapter:source0_ready
	wire    [1:0] burst_adapter_source0_channel;                                                       // burst_adapter:source0_channel -> h2f_slave_0_s0_translator_avalon_universal_slave_0_agent:cp_channel
	wire          cmd_xbar_demux_src0_endofpacket;                                                     // cmd_xbar_demux:src0_endofpacket -> crosser:in_endofpacket
	wire          cmd_xbar_demux_src0_valid;                                                           // cmd_xbar_demux:src0_valid -> crosser:in_valid
	wire          cmd_xbar_demux_src0_startofpacket;                                                   // cmd_xbar_demux:src0_startofpacket -> crosser:in_startofpacket
	wire  [233:0] cmd_xbar_demux_src0_data;                                                            // cmd_xbar_demux:src0_data -> crosser:in_data
	wire    [1:0] cmd_xbar_demux_src0_channel;                                                         // cmd_xbar_demux:src0_channel -> crosser:in_channel
	wire          cmd_xbar_demux_src0_ready;                                                           // crosser:in_ready -> cmd_xbar_demux:src0_ready
	wire          crosser_out_endofpacket;                                                             // crosser:out_endofpacket -> cmd_xbar_mux:sink0_endofpacket
	wire          crosser_out_valid;                                                                   // crosser:out_valid -> cmd_xbar_mux:sink0_valid
	wire          crosser_out_startofpacket;                                                           // crosser:out_startofpacket -> cmd_xbar_mux:sink0_startofpacket
	wire  [233:0] crosser_out_data;                                                                    // crosser:out_data -> cmd_xbar_mux:sink0_data
	wire    [1:0] crosser_out_channel;                                                                 // crosser:out_channel -> cmd_xbar_mux:sink0_channel
	wire          crosser_out_ready;                                                                   // cmd_xbar_mux:sink0_ready -> crosser:out_ready
	wire          cmd_xbar_demux_001_src0_endofpacket;                                                 // cmd_xbar_demux_001:src0_endofpacket -> crosser_001:in_endofpacket
	wire          cmd_xbar_demux_001_src0_valid;                                                       // cmd_xbar_demux_001:src0_valid -> crosser_001:in_valid
	wire          cmd_xbar_demux_001_src0_startofpacket;                                               // cmd_xbar_demux_001:src0_startofpacket -> crosser_001:in_startofpacket
	wire  [233:0] cmd_xbar_demux_001_src0_data;                                                        // cmd_xbar_demux_001:src0_data -> crosser_001:in_data
	wire    [1:0] cmd_xbar_demux_001_src0_channel;                                                     // cmd_xbar_demux_001:src0_channel -> crosser_001:in_channel
	wire          cmd_xbar_demux_001_src0_ready;                                                       // crosser_001:in_ready -> cmd_xbar_demux_001:src0_ready
	wire          crosser_001_out_endofpacket;                                                         // crosser_001:out_endofpacket -> cmd_xbar_mux:sink1_endofpacket
	wire          crosser_001_out_valid;                                                               // crosser_001:out_valid -> cmd_xbar_mux:sink1_valid
	wire          crosser_001_out_startofpacket;                                                       // crosser_001:out_startofpacket -> cmd_xbar_mux:sink1_startofpacket
	wire  [233:0] crosser_001_out_data;                                                                // crosser_001:out_data -> cmd_xbar_mux:sink1_data
	wire    [1:0] crosser_001_out_channel;                                                             // crosser_001:out_channel -> cmd_xbar_mux:sink1_channel
	wire          crosser_001_out_ready;                                                               // cmd_xbar_mux:sink1_ready -> crosser_001:out_ready
	wire          rsp_xbar_demux_src0_endofpacket;                                                     // rsp_xbar_demux:src0_endofpacket -> crosser_002:in_endofpacket
	wire          rsp_xbar_demux_src0_valid;                                                           // rsp_xbar_demux:src0_valid -> crosser_002:in_valid
	wire          rsp_xbar_demux_src0_startofpacket;                                                   // rsp_xbar_demux:src0_startofpacket -> crosser_002:in_startofpacket
	wire  [233:0] rsp_xbar_demux_src0_data;                                                            // rsp_xbar_demux:src0_data -> crosser_002:in_data
	wire    [1:0] rsp_xbar_demux_src0_channel;                                                         // rsp_xbar_demux:src0_channel -> crosser_002:in_channel
	wire          rsp_xbar_demux_src0_ready;                                                           // crosser_002:in_ready -> rsp_xbar_demux:src0_ready
	wire          crosser_002_out_endofpacket;                                                         // crosser_002:out_endofpacket -> rsp_xbar_mux:sink0_endofpacket
	wire          crosser_002_out_valid;                                                               // crosser_002:out_valid -> rsp_xbar_mux:sink0_valid
	wire          crosser_002_out_startofpacket;                                                       // crosser_002:out_startofpacket -> rsp_xbar_mux:sink0_startofpacket
	wire  [233:0] crosser_002_out_data;                                                                // crosser_002:out_data -> rsp_xbar_mux:sink0_data
	wire    [1:0] crosser_002_out_channel;                                                             // crosser_002:out_channel -> rsp_xbar_mux:sink0_channel
	wire          crosser_002_out_ready;                                                               // rsp_xbar_mux:sink0_ready -> crosser_002:out_ready
	wire          rsp_xbar_demux_src1_endofpacket;                                                     // rsp_xbar_demux:src1_endofpacket -> crosser_003:in_endofpacket
	wire          rsp_xbar_demux_src1_valid;                                                           // rsp_xbar_demux:src1_valid -> crosser_003:in_valid
	wire          rsp_xbar_demux_src1_startofpacket;                                                   // rsp_xbar_demux:src1_startofpacket -> crosser_003:in_startofpacket
	wire  [233:0] rsp_xbar_demux_src1_data;                                                            // rsp_xbar_demux:src1_data -> crosser_003:in_data
	wire    [1:0] rsp_xbar_demux_src1_channel;                                                         // rsp_xbar_demux:src1_channel -> crosser_003:in_channel
	wire          rsp_xbar_demux_src1_ready;                                                           // crosser_003:in_ready -> rsp_xbar_demux:src1_ready
	wire          crosser_003_out_endofpacket;                                                         // crosser_003:out_endofpacket -> rsp_xbar_mux_001:sink0_endofpacket
	wire          crosser_003_out_valid;                                                               // crosser_003:out_valid -> rsp_xbar_mux_001:sink0_valid
	wire          crosser_003_out_startofpacket;                                                       // crosser_003:out_startofpacket -> rsp_xbar_mux_001:sink0_startofpacket
	wire  [233:0] crosser_003_out_data;                                                                // crosser_003:out_data -> rsp_xbar_mux_001:sink0_data
	wire    [1:0] crosser_003_out_channel;                                                             // crosser_003:out_channel -> rsp_xbar_mux_001:sink0_channel
	wire          crosser_003_out_ready;                                                               // rsp_xbar_mux_001:sink0_ready -> crosser_003:out_ready

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (26),
		.AV_DATA_W                      (128),
		.UAV_DATA_W                     (128),
		.AV_BURSTCOUNT_W                (6),
		.AV_BYTEENABLE_W                (16),
		.UAV_BYTEENABLE_W               (16),
		.UAV_ADDRESS_W                  (30),
		.UAV_BURSTCOUNT_W               (10),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (16),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) h2f_slave_0_s0_translator (
		.clk                      (clock_bridge_0_out_clk_clk),                                                //                      clk.clk
		.reset                    (h2f_slave_0_reset_reset_bridge_in_reset_reset),                             //                    reset.reset
		.uav_address              (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_address),       // avalon_universal_slave_0.address
		.uav_burstcount           (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_burstcount),    //                         .burstcount
		.uav_read                 (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_read),          //                         .read
		.uav_write                (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_write),         //                         .write
		.uav_waitrequest          (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid        (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_readdatavalid), //                         .readdatavalid
		.uav_byteenable           (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_byteenable),    //                         .byteenable
		.uav_readdata             (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_readdata),      //                         .readdata
		.uav_writedata            (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_writedata),     //                         .writedata
		.uav_lock                 (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_lock),          //                         .lock
		.uav_debugaccess          (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_debugaccess),   //                         .debugaccess
		.av_address               (h2f_slave_0_s0_address),                                                    //      avalon_anti_slave_0.address
		.av_write                 (h2f_slave_0_s0_write),                                                      //                         .write
		.av_read                  (h2f_slave_0_s0_read),                                                       //                         .read
		.av_readdata              (h2f_slave_0_s0_readdata),                                                   //                         .readdata
		.av_writedata             (h2f_slave_0_s0_writedata),                                                  //                         .writedata
		.av_burstcount            (h2f_slave_0_s0_burstcount),                                                 //                         .burstcount
		.av_byteenable            (h2f_slave_0_s0_byteenable),                                                 //                         .byteenable
		.av_readdatavalid         (h2f_slave_0_s0_readdatavalid),                                              //                         .readdatavalid
		.av_waitrequest           (h2f_slave_0_s0_waitrequest),                                                //                         .waitrequest
		.av_debugaccess           (h2f_slave_0_s0_debugaccess),                                                //                         .debugaccess
		.av_begintransfer         (),                                                                          //              (terminated)
		.av_beginbursttransfer    (),                                                                          //              (terminated)
		.av_writebyteenable       (),                                                                          //              (terminated)
		.av_lock                  (),                                                                          //              (terminated)
		.av_chipselect            (),                                                                          //              (terminated)
		.av_clken                 (),                                                                          //              (terminated)
		.uav_clken                (1'b0),                                                                      //              (terminated)
		.av_outputenable          (),                                                                          //              (terminated)
		.uav_response             (),                                                                          //              (terminated)
		.av_response              (2'b00),                                                                     //              (terminated)
		.uav_writeresponserequest (1'b0),                                                                      //              (terminated)
		.uav_writeresponsevalid   (),                                                                          //              (terminated)
		.av_writeresponserequest  (),                                                                          //              (terminated)
		.av_writeresponsevalid    (1'b0)                                                                       //              (terminated)
	);

	altera_merlin_axi_master_ni #(
		.ID_WIDTH                  (12),
		.ADDR_WIDTH                (30),
		.RDATA_WIDTH               (128),
		.WDATA_WIDTH               (128),
		.ADDR_USER_WIDTH           (1),
		.DATA_USER_WIDTH           (1),
		.AXI_BURST_LENGTH_WIDTH    (4),
		.AXI_LOCK_WIDTH            (2),
		.AXI_VERSION               ("AXI3"),
		.WRITE_ISSUING_CAPABILITY  (8),
		.READ_ISSUING_CAPABILITY   (8),
		.PKT_BEGIN_BURST           (206),
		.PKT_CACHE_H               (228),
		.PKT_CACHE_L               (225),
		.PKT_ADDR_SIDEBAND_H       (204),
		.PKT_ADDR_SIDEBAND_L       (204),
		.PKT_PROTECTION_H          (224),
		.PKT_PROTECTION_L          (222),
		.PKT_BURST_SIZE_H          (201),
		.PKT_BURST_SIZE_L          (199),
		.PKT_BURST_TYPE_H          (203),
		.PKT_BURST_TYPE_L          (202),
		.PKT_RESPONSE_STATUS_L     (229),
		.PKT_RESPONSE_STATUS_H     (230),
		.PKT_BURSTWRAP_H           (198),
		.PKT_BURSTWRAP_L           (190),
		.PKT_BYTE_CNT_H            (189),
		.PKT_BYTE_CNT_L            (180),
		.PKT_ADDR_H                (173),
		.PKT_ADDR_L                (144),
		.PKT_TRANS_EXCLUSIVE       (179),
		.PKT_TRANS_LOCK            (178),
		.PKT_TRANS_COMPRESSED_READ (174),
		.PKT_TRANS_POSTED          (175),
		.PKT_TRANS_WRITE           (176),
		.PKT_TRANS_READ            (177),
		.PKT_DATA_H                (127),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (143),
		.PKT_BYTEEN_L              (128),
		.PKT_SRC_ID_H              (208),
		.PKT_SRC_ID_L              (208),
		.PKT_DEST_ID_H             (209),
		.PKT_DEST_ID_L             (209),
		.PKT_THREAD_ID_H           (221),
		.PKT_THREAD_ID_L           (210),
		.PKT_QOS_L                 (207),
		.PKT_QOS_H                 (207),
		.PKT_ORI_BURST_SIZE_L      (231),
		.PKT_ORI_BURST_SIZE_H      (233),
		.PKT_DATA_SIDEBAND_H       (205),
		.PKT_DATA_SIDEBAND_L       (205),
		.ST_DATA_W                 (234),
		.ST_CHANNEL_W              (2),
		.ID                        (0)
	) hps_0_h2f_axi_master_agent (
		.aclk                   (hps_0_h2f_user0_clock_clk),                                         //              clk.clk
		.aresetn                (~hps_0_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), //        clk_reset.reset_n
		.write_cp_valid         (hps_0_h2f_axi_master_agent_write_cp_valid),                         //         write_cp.valid
		.write_cp_data          (hps_0_h2f_axi_master_agent_write_cp_data),                          //                 .data
		.write_cp_startofpacket (hps_0_h2f_axi_master_agent_write_cp_startofpacket),                 //                 .startofpacket
		.write_cp_endofpacket   (hps_0_h2f_axi_master_agent_write_cp_endofpacket),                   //                 .endofpacket
		.write_cp_ready         (hps_0_h2f_axi_master_agent_write_cp_ready),                         //                 .ready
		.write_rp_valid         (rsp_xbar_mux_src_valid),                                            //         write_rp.valid
		.write_rp_data          (rsp_xbar_mux_src_data),                                             //                 .data
		.write_rp_channel       (rsp_xbar_mux_src_channel),                                          //                 .channel
		.write_rp_startofpacket (rsp_xbar_mux_src_startofpacket),                                    //                 .startofpacket
		.write_rp_endofpacket   (rsp_xbar_mux_src_endofpacket),                                      //                 .endofpacket
		.write_rp_ready         (rsp_xbar_mux_src_ready),                                            //                 .ready
		.read_cp_valid          (hps_0_h2f_axi_master_agent_read_cp_valid),                          //          read_cp.valid
		.read_cp_data           (hps_0_h2f_axi_master_agent_read_cp_data),                           //                 .data
		.read_cp_startofpacket  (hps_0_h2f_axi_master_agent_read_cp_startofpacket),                  //                 .startofpacket
		.read_cp_endofpacket    (hps_0_h2f_axi_master_agent_read_cp_endofpacket),                    //                 .endofpacket
		.read_cp_ready          (hps_0_h2f_axi_master_agent_read_cp_ready),                          //                 .ready
		.read_rp_valid          (rsp_xbar_mux_001_src_valid),                                        //          read_rp.valid
		.read_rp_data           (rsp_xbar_mux_001_src_data),                                         //                 .data
		.read_rp_channel        (rsp_xbar_mux_001_src_channel),                                      //                 .channel
		.read_rp_startofpacket  (rsp_xbar_mux_001_src_startofpacket),                                //                 .startofpacket
		.read_rp_endofpacket    (rsp_xbar_mux_001_src_endofpacket),                                  //                 .endofpacket
		.read_rp_ready          (rsp_xbar_mux_001_src_ready),                                        //                 .ready
		.awid                   (hps_0_h2f_axi_master_awid),                                         // altera_axi_slave.awid
		.awaddr                 (hps_0_h2f_axi_master_awaddr),                                       //                 .awaddr
		.awlen                  (hps_0_h2f_axi_master_awlen),                                        //                 .awlen
		.awsize                 (hps_0_h2f_axi_master_awsize),                                       //                 .awsize
		.awburst                (hps_0_h2f_axi_master_awburst),                                      //                 .awburst
		.awlock                 (hps_0_h2f_axi_master_awlock),                                       //                 .awlock
		.awcache                (hps_0_h2f_axi_master_awcache),                                      //                 .awcache
		.awprot                 (hps_0_h2f_axi_master_awprot),                                       //                 .awprot
		.awvalid                (hps_0_h2f_axi_master_awvalid),                                      //                 .awvalid
		.awready                (hps_0_h2f_axi_master_awready),                                      //                 .awready
		.wid                    (hps_0_h2f_axi_master_wid),                                          //                 .wid
		.wdata                  (hps_0_h2f_axi_master_wdata),                                        //                 .wdata
		.wstrb                  (hps_0_h2f_axi_master_wstrb),                                        //                 .wstrb
		.wlast                  (hps_0_h2f_axi_master_wlast),                                        //                 .wlast
		.wvalid                 (hps_0_h2f_axi_master_wvalid),                                       //                 .wvalid
		.wready                 (hps_0_h2f_axi_master_wready),                                       //                 .wready
		.bid                    (hps_0_h2f_axi_master_bid),                                          //                 .bid
		.bresp                  (hps_0_h2f_axi_master_bresp),                                        //                 .bresp
		.bvalid                 (hps_0_h2f_axi_master_bvalid),                                       //                 .bvalid
		.bready                 (hps_0_h2f_axi_master_bready),                                       //                 .bready
		.arid                   (hps_0_h2f_axi_master_arid),                                         //                 .arid
		.araddr                 (hps_0_h2f_axi_master_araddr),                                       //                 .araddr
		.arlen                  (hps_0_h2f_axi_master_arlen),                                        //                 .arlen
		.arsize                 (hps_0_h2f_axi_master_arsize),                                       //                 .arsize
		.arburst                (hps_0_h2f_axi_master_arburst),                                      //                 .arburst
		.arlock                 (hps_0_h2f_axi_master_arlock),                                       //                 .arlock
		.arcache                (hps_0_h2f_axi_master_arcache),                                      //                 .arcache
		.arprot                 (hps_0_h2f_axi_master_arprot),                                       //                 .arprot
		.arvalid                (hps_0_h2f_axi_master_arvalid),                                      //                 .arvalid
		.arready                (hps_0_h2f_axi_master_arready),                                      //                 .arready
		.rid                    (hps_0_h2f_axi_master_rid),                                          //                 .rid
		.rdata                  (hps_0_h2f_axi_master_rdata),                                        //                 .rdata
		.rresp                  (hps_0_h2f_axi_master_rresp),                                        //                 .rresp
		.rlast                  (hps_0_h2f_axi_master_rlast),                                        //                 .rlast
		.rvalid                 (hps_0_h2f_axi_master_rvalid),                                       //                 .rvalid
		.rready                 (hps_0_h2f_axi_master_rready),                                       //                 .rready
		.awuser                 (1'b0),                                                              //      (terminated)
		.aruser                 (1'b0),                                                              //      (terminated)
		.awqos                  (4'b0000),                                                           //      (terminated)
		.arqos                  (4'b0000),                                                           //      (terminated)
		.awregion               (4'b0000),                                                           //      (terminated)
		.arregion               (4'b0000),                                                           //      (terminated)
		.wuser                  (8'b00000000),                                                       //      (terminated)
		.ruser                  (),                                                                  //      (terminated)
		.buser                  ()                                                                   //      (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_DATA_H                (127),
		.PKT_DATA_L                (0),
		.PKT_BEGIN_BURST           (206),
		.PKT_SYMBOL_W              (8),
		.PKT_BYTEEN_H              (143),
		.PKT_BYTEEN_L              (128),
		.PKT_ADDR_H                (173),
		.PKT_ADDR_L                (144),
		.PKT_TRANS_COMPRESSED_READ (174),
		.PKT_TRANS_POSTED          (175),
		.PKT_TRANS_WRITE           (176),
		.PKT_TRANS_READ            (177),
		.PKT_TRANS_LOCK            (178),
		.PKT_SRC_ID_H              (208),
		.PKT_SRC_ID_L              (208),
		.PKT_DEST_ID_H             (209),
		.PKT_DEST_ID_L             (209),
		.PKT_BURSTWRAP_H           (198),
		.PKT_BURSTWRAP_L           (190),
		.PKT_BYTE_CNT_H            (189),
		.PKT_BYTE_CNT_L            (180),
		.PKT_PROTECTION_H          (224),
		.PKT_PROTECTION_L          (222),
		.PKT_RESPONSE_STATUS_H     (230),
		.PKT_RESPONSE_STATUS_L     (229),
		.PKT_BURST_SIZE_H          (201),
		.PKT_BURST_SIZE_L          (199),
		.PKT_ORI_BURST_SIZE_L      (231),
		.PKT_ORI_BURST_SIZE_H      (233),
		.ST_CHANNEL_W              (2),
		.ST_DATA_W                 (234),
		.AVS_BURSTCOUNT_W          (10),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) h2f_slave_0_s0_translator_avalon_universal_slave_0_agent (
		.clk                     (clock_bridge_0_out_clk_clk),                                                          //             clk.clk
		.reset                   (h2f_slave_0_reset_reset_bridge_in_reset_reset),                                       //       clk_reset.reset
		.m0_address              (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_address),                 //              m0.address
		.m0_burstcount           (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_burstcount),              //                .burstcount
		.m0_byteenable           (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_byteenable),              //                .byteenable
		.m0_debugaccess          (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_debugaccess),             //                .debugaccess
		.m0_lock                 (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_lock),                    //                .lock
		.m0_readdata             (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_readdata),                //                .readdata
		.m0_readdatavalid        (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_readdatavalid),           //                .readdatavalid
		.m0_read                 (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_read),                    //                .read
		.m0_waitrequest          (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_waitrequest),             //                .waitrequest
		.m0_writedata            (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_writedata),               //                .writedata
		.m0_write                (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_m0_write),                   //                .write
		.rp_endofpacket          (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rp_endofpacket),             //              rp.endofpacket
		.rp_ready                (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rp_ready),                   //                .ready
		.rp_valid                (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rp_valid),                   //                .valid
		.rp_data                 (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rp_data),                    //                .data
		.rp_startofpacket        (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rp_startofpacket),           //                .startofpacket
		.cp_ready                (burst_adapter_source0_ready),                                                         //              cp.ready
		.cp_valid                (burst_adapter_source0_valid),                                                         //                .valid
		.cp_data                 (burst_adapter_source0_data),                                                          //                .data
		.cp_startofpacket        (burst_adapter_source0_startofpacket),                                                 //                .startofpacket
		.cp_endofpacket          (burst_adapter_source0_endofpacket),                                                   //                .endofpacket
		.cp_channel              (burst_adapter_source0_channel),                                                       //                .channel
		.rf_sink_ready           (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_ready),         //         rf_sink.ready
		.rf_sink_valid           (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_valid),         //                .valid
		.rf_sink_startofpacket   (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_startofpacket), //                .startofpacket
		.rf_sink_endofpacket     (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_endofpacket),   //                .endofpacket
		.rf_sink_data            (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_data),          //                .data
		.rf_source_ready         (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rf_source_ready),            //       rf_source.ready
		.rf_source_valid         (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rf_source_valid),            //                .valid
		.rf_source_startofpacket (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rf_source_startofpacket),    //                .startofpacket
		.rf_source_endofpacket   (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rf_source_endofpacket),      //                .endofpacket
		.rf_source_data          (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rf_source_data),             //                .data
		.rdata_fifo_sink_ready   (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo_out_ready),       // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo_out_valid),       //                .valid
		.rdata_fifo_sink_data    (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo_out_data),        //                .data
		.rdata_fifo_src_ready    (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo_src_ready),       //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo_src_valid),       //                .valid
		.rdata_fifo_src_data     (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo_src_data),        //                .data
		.m0_response             (2'b00),                                                                               //     (terminated)
		.m0_writeresponserequest (),                                                                                    //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                                                                 //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (235),
		.FIFO_DEPTH          (5),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo (
		.clk               (clock_bridge_0_out_clk_clk),                                                          //       clk.clk
		.reset             (h2f_slave_0_reset_reset_bridge_in_reset_reset),                                       // clk_reset.reset
		.in_data           (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rf_source_data),             //        in.data
		.in_valid          (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rf_source_valid),            //          .valid
		.in_ready          (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rf_source_ready),            //          .ready
		.in_startofpacket  (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rf_source_startofpacket),    //          .startofpacket
		.in_endofpacket    (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rf_source_endofpacket),      //          .endofpacket
		.out_data          (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_data),          //       out.data
		.out_valid         (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_valid),         //          .valid
		.out_ready         (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_ready),         //          .ready
		.out_startofpacket (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_startofpacket), //          .startofpacket
		.out_endofpacket   (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_endofpacket),   //          .endofpacket
		.csr_address       (2'b00),                                                                               // (terminated)
		.csr_read          (1'b0),                                                                                // (terminated)
		.csr_write         (1'b0),                                                                                // (terminated)
		.csr_readdata      (),                                                                                    // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                                                // (terminated)
		.almost_full_data  (),                                                                                    // (terminated)
		.almost_empty_data (),                                                                                    // (terminated)
		.in_empty          (1'b0),                                                                                // (terminated)
		.out_empty         (),                                                                                    // (terminated)
		.in_error          (1'b0),                                                                                // (terminated)
		.out_error         (),                                                                                    // (terminated)
		.in_channel        (1'b0),                                                                                // (terminated)
		.out_channel       ()                                                                                     // (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (130),
		.FIFO_DEPTH          (128),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (0),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (3),
		.USE_MEMORY_BLOCKS   (1),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo (
		.clk               (clock_bridge_0_out_clk_clk),                                                    //       clk.clk
		.reset             (h2f_slave_0_reset_reset_bridge_in_reset_reset),                                 // clk_reset.reset
		.in_data           (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo_src_data),  //        in.data
		.in_valid          (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo_src_valid), //          .valid
		.in_ready          (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo_src_ready), //          .ready
		.out_data          (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo_out_data),  //       out.data
		.out_valid         (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo_out_valid), //          .valid
		.out_ready         (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rdata_fifo_out_ready), //          .ready
		.csr_address       (2'b00),                                                                         // (terminated)
		.csr_read          (1'b0),                                                                          // (terminated)
		.csr_write         (1'b0),                                                                          // (terminated)
		.csr_readdata      (),                                                                              // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                                          // (terminated)
		.almost_full_data  (),                                                                              // (terminated)
		.almost_empty_data (),                                                                              // (terminated)
		.in_startofpacket  (1'b0),                                                                          // (terminated)
		.in_endofpacket    (1'b0),                                                                          // (terminated)
		.out_startofpacket (),                                                                              // (terminated)
		.out_endofpacket   (),                                                                              // (terminated)
		.in_empty          (1'b0),                                                                          // (terminated)
		.out_empty         (),                                                                              // (terminated)
		.in_error          (1'b0),                                                                          // (terminated)
		.out_error         (),                                                                              // (terminated)
		.in_channel        (1'b0),                                                                          // (terminated)
		.out_channel       ()                                                                               // (terminated)
	);

	soc_system_mm_interconnect_1_addr_router addr_router (
		.sink_ready         (hps_0_h2f_axi_master_agent_write_cp_ready),                        //      sink.ready
		.sink_valid         (hps_0_h2f_axi_master_agent_write_cp_valid),                        //          .valid
		.sink_data          (hps_0_h2f_axi_master_agent_write_cp_data),                         //          .data
		.sink_startofpacket (hps_0_h2f_axi_master_agent_write_cp_startofpacket),                //          .startofpacket
		.sink_endofpacket   (hps_0_h2f_axi_master_agent_write_cp_endofpacket),                  //          .endofpacket
		.clk                (hps_0_h2f_user0_clock_clk),                                        //       clk.clk
		.reset              (hps_0_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (addr_router_src_ready),                                            //       src.ready
		.src_valid          (addr_router_src_valid),                                            //          .valid
		.src_data           (addr_router_src_data),                                             //          .data
		.src_channel        (addr_router_src_channel),                                          //          .channel
		.src_startofpacket  (addr_router_src_startofpacket),                                    //          .startofpacket
		.src_endofpacket    (addr_router_src_endofpacket)                                       //          .endofpacket
	);

	soc_system_mm_interconnect_1_addr_router addr_router_001 (
		.sink_ready         (hps_0_h2f_axi_master_agent_read_cp_ready),                         //      sink.ready
		.sink_valid         (hps_0_h2f_axi_master_agent_read_cp_valid),                         //          .valid
		.sink_data          (hps_0_h2f_axi_master_agent_read_cp_data),                          //          .data
		.sink_startofpacket (hps_0_h2f_axi_master_agent_read_cp_startofpacket),                 //          .startofpacket
		.sink_endofpacket   (hps_0_h2f_axi_master_agent_read_cp_endofpacket),                   //          .endofpacket
		.clk                (hps_0_h2f_user0_clock_clk),                                        //       clk.clk
		.reset              (hps_0_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (addr_router_001_src_ready),                                        //       src.ready
		.src_valid          (addr_router_001_src_valid),                                        //          .valid
		.src_data           (addr_router_001_src_data),                                         //          .data
		.src_channel        (addr_router_001_src_channel),                                      //          .channel
		.src_startofpacket  (addr_router_001_src_startofpacket),                                //          .startofpacket
		.src_endofpacket    (addr_router_001_src_endofpacket)                                   //          .endofpacket
	);

	soc_system_mm_interconnect_1_id_router id_router (
		.sink_ready         (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rp_ready),         //      sink.ready
		.sink_valid         (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rp_valid),         //          .valid
		.sink_data          (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rp_data),          //          .data
		.sink_startofpacket (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rp_startofpacket), //          .startofpacket
		.sink_endofpacket   (h2f_slave_0_s0_translator_avalon_universal_slave_0_agent_rp_endofpacket),   //          .endofpacket
		.clk                (clock_bridge_0_out_clk_clk),                                                //       clk.clk
		.reset              (h2f_slave_0_reset_reset_bridge_in_reset_reset),                             // clk_reset.reset
		.src_ready          (id_router_src_ready),                                                       //       src.ready
		.src_valid          (id_router_src_valid),                                                       //          .valid
		.src_data           (id_router_src_data),                                                        //          .data
		.src_channel        (id_router_src_channel),                                                     //          .channel
		.src_startofpacket  (id_router_src_startofpacket),                                               //          .startofpacket
		.src_endofpacket    (id_router_src_endofpacket)                                                  //          .endofpacket
	);

	altera_merlin_burst_adapter #(
		.PKT_ADDR_H                (173),
		.PKT_ADDR_L                (144),
		.PKT_BEGIN_BURST           (206),
		.PKT_BYTE_CNT_H            (189),
		.PKT_BYTE_CNT_L            (180),
		.PKT_BYTEEN_H              (143),
		.PKT_BYTEEN_L              (128),
		.PKT_BURST_SIZE_H          (201),
		.PKT_BURST_SIZE_L          (199),
		.PKT_BURST_TYPE_H          (203),
		.PKT_BURST_TYPE_L          (202),
		.PKT_BURSTWRAP_H           (198),
		.PKT_BURSTWRAP_L           (190),
		.PKT_TRANS_COMPRESSED_READ (174),
		.PKT_TRANS_WRITE           (176),
		.PKT_TRANS_READ            (177),
		.OUT_NARROW_SIZE           (0),
		.IN_NARROW_SIZE            (1),
		.OUT_FIXED                 (0),
		.OUT_COMPLETE_WRAP         (0),
		.ST_DATA_W                 (234),
		.ST_CHANNEL_W              (2),
		.OUT_BYTE_CNT_H            (189),
		.OUT_BURSTWRAP_H           (198),
		.COMPRESSED_READ_SUPPORT   (1),
		.BYTEENABLE_SYNTHESIS      (1),
		.PIPE_INPUTS               (0),
		.NO_WRAP_SUPPORT           (0),
		.BURSTWRAP_CONST_MASK      (0),
		.BURSTWRAP_CONST_VALUE     (0)
	) burst_adapter (
		.clk                   (clock_bridge_0_out_clk_clk),                    //       cr0.clk
		.reset                 (h2f_slave_0_reset_reset_bridge_in_reset_reset), // cr0_reset.reset
		.sink0_valid           (cmd_xbar_mux_src_valid),                        //     sink0.valid
		.sink0_data            (cmd_xbar_mux_src_data),                         //          .data
		.sink0_channel         (cmd_xbar_mux_src_channel),                      //          .channel
		.sink0_startofpacket   (cmd_xbar_mux_src_startofpacket),                //          .startofpacket
		.sink0_endofpacket     (cmd_xbar_mux_src_endofpacket),                  //          .endofpacket
		.sink0_ready           (cmd_xbar_mux_src_ready),                        //          .ready
		.source0_valid         (burst_adapter_source0_valid),                   //   source0.valid
		.source0_data          (burst_adapter_source0_data),                    //          .data
		.source0_channel       (burst_adapter_source0_channel),                 //          .channel
		.source0_startofpacket (burst_adapter_source0_startofpacket),           //          .startofpacket
		.source0_endofpacket   (burst_adapter_source0_endofpacket),             //          .endofpacket
		.source0_ready         (burst_adapter_source0_ready)                    //          .ready
	);

	soc_system_mm_interconnect_1_cmd_xbar_demux cmd_xbar_demux (
		.clk                (hps_0_h2f_user0_clock_clk),                                        //       clk.clk
		.reset              (hps_0_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (addr_router_src_ready),                                            //      sink.ready
		.sink_channel       (addr_router_src_channel),                                          //          .channel
		.sink_data          (addr_router_src_data),                                             //          .data
		.sink_startofpacket (addr_router_src_startofpacket),                                    //          .startofpacket
		.sink_endofpacket   (addr_router_src_endofpacket),                                      //          .endofpacket
		.sink_valid         (addr_router_src_valid),                                            //          .valid
		.src0_ready         (cmd_xbar_demux_src0_ready),                                        //      src0.ready
		.src0_valid         (cmd_xbar_demux_src0_valid),                                        //          .valid
		.src0_data          (cmd_xbar_demux_src0_data),                                         //          .data
		.src0_channel       (cmd_xbar_demux_src0_channel),                                      //          .channel
		.src0_startofpacket (cmd_xbar_demux_src0_startofpacket),                                //          .startofpacket
		.src0_endofpacket   (cmd_xbar_demux_src0_endofpacket)                                   //          .endofpacket
	);

	soc_system_mm_interconnect_1_cmd_xbar_demux cmd_xbar_demux_001 (
		.clk                (hps_0_h2f_user0_clock_clk),                                        //       clk.clk
		.reset              (hps_0_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (addr_router_001_src_ready),                                        //      sink.ready
		.sink_channel       (addr_router_001_src_channel),                                      //          .channel
		.sink_data          (addr_router_001_src_data),                                         //          .data
		.sink_startofpacket (addr_router_001_src_startofpacket),                                //          .startofpacket
		.sink_endofpacket   (addr_router_001_src_endofpacket),                                  //          .endofpacket
		.sink_valid         (addr_router_001_src_valid),                                        //          .valid
		.src0_ready         (cmd_xbar_demux_001_src0_ready),                                    //      src0.ready
		.src0_valid         (cmd_xbar_demux_001_src0_valid),                                    //          .valid
		.src0_data          (cmd_xbar_demux_001_src0_data),                                     //          .data
		.src0_channel       (cmd_xbar_demux_001_src0_channel),                                  //          .channel
		.src0_startofpacket (cmd_xbar_demux_001_src0_startofpacket),                            //          .startofpacket
		.src0_endofpacket   (cmd_xbar_demux_001_src0_endofpacket)                               //          .endofpacket
	);

	soc_system_mm_interconnect_1_cmd_xbar_mux cmd_xbar_mux (
		.clk                 (clock_bridge_0_out_clk_clk),                    //       clk.clk
		.reset               (h2f_slave_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_xbar_mux_src_ready),                        //       src.ready
		.src_valid           (cmd_xbar_mux_src_valid),                        //          .valid
		.src_data            (cmd_xbar_mux_src_data),                         //          .data
		.src_channel         (cmd_xbar_mux_src_channel),                      //          .channel
		.src_startofpacket   (cmd_xbar_mux_src_startofpacket),                //          .startofpacket
		.src_endofpacket     (cmd_xbar_mux_src_endofpacket),                  //          .endofpacket
		.sink0_ready         (crosser_out_ready),                             //     sink0.ready
		.sink0_valid         (crosser_out_valid),                             //          .valid
		.sink0_channel       (crosser_out_channel),                           //          .channel
		.sink0_data          (crosser_out_data),                              //          .data
		.sink0_startofpacket (crosser_out_startofpacket),                     //          .startofpacket
		.sink0_endofpacket   (crosser_out_endofpacket),                       //          .endofpacket
		.sink1_ready         (crosser_001_out_ready),                         //     sink1.ready
		.sink1_valid         (crosser_001_out_valid),                         //          .valid
		.sink1_channel       (crosser_001_out_channel),                       //          .channel
		.sink1_data          (crosser_001_out_data),                          //          .data
		.sink1_startofpacket (crosser_001_out_startofpacket),                 //          .startofpacket
		.sink1_endofpacket   (crosser_001_out_endofpacket)                    //          .endofpacket
	);

	soc_system_mm_interconnect_1_rsp_xbar_demux rsp_xbar_demux (
		.clk                (clock_bridge_0_out_clk_clk),                    //       clk.clk
		.reset              (h2f_slave_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (id_router_src_ready),                           //      sink.ready
		.sink_channel       (id_router_src_channel),                         //          .channel
		.sink_data          (id_router_src_data),                            //          .data
		.sink_startofpacket (id_router_src_startofpacket),                   //          .startofpacket
		.sink_endofpacket   (id_router_src_endofpacket),                     //          .endofpacket
		.sink_valid         (id_router_src_valid),                           //          .valid
		.src0_ready         (rsp_xbar_demux_src0_ready),                     //      src0.ready
		.src0_valid         (rsp_xbar_demux_src0_valid),                     //          .valid
		.src0_data          (rsp_xbar_demux_src0_data),                      //          .data
		.src0_channel       (rsp_xbar_demux_src0_channel),                   //          .channel
		.src0_startofpacket (rsp_xbar_demux_src0_startofpacket),             //          .startofpacket
		.src0_endofpacket   (rsp_xbar_demux_src0_endofpacket),               //          .endofpacket
		.src1_ready         (rsp_xbar_demux_src1_ready),                     //      src1.ready
		.src1_valid         (rsp_xbar_demux_src1_valid),                     //          .valid
		.src1_data          (rsp_xbar_demux_src1_data),                      //          .data
		.src1_channel       (rsp_xbar_demux_src1_channel),                   //          .channel
		.src1_startofpacket (rsp_xbar_demux_src1_startofpacket),             //          .startofpacket
		.src1_endofpacket   (rsp_xbar_demux_src1_endofpacket)                //          .endofpacket
	);

	soc_system_mm_interconnect_1_rsp_xbar_mux rsp_xbar_mux (
		.clk                 (hps_0_h2f_user0_clock_clk),                                        //       clk.clk
		.reset               (hps_0_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_xbar_mux_src_ready),                                           //       src.ready
		.src_valid           (rsp_xbar_mux_src_valid),                                           //          .valid
		.src_data            (rsp_xbar_mux_src_data),                                            //          .data
		.src_channel         (rsp_xbar_mux_src_channel),                                         //          .channel
		.src_startofpacket   (rsp_xbar_mux_src_startofpacket),                                   //          .startofpacket
		.src_endofpacket     (rsp_xbar_mux_src_endofpacket),                                     //          .endofpacket
		.sink0_ready         (crosser_002_out_ready),                                            //     sink0.ready
		.sink0_valid         (crosser_002_out_valid),                                            //          .valid
		.sink0_channel       (crosser_002_out_channel),                                          //          .channel
		.sink0_data          (crosser_002_out_data),                                             //          .data
		.sink0_startofpacket (crosser_002_out_startofpacket),                                    //          .startofpacket
		.sink0_endofpacket   (crosser_002_out_endofpacket)                                       //          .endofpacket
	);

	soc_system_mm_interconnect_1_rsp_xbar_mux rsp_xbar_mux_001 (
		.clk                 (hps_0_h2f_user0_clock_clk),                                        //       clk.clk
		.reset               (hps_0_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_xbar_mux_001_src_ready),                                       //       src.ready
		.src_valid           (rsp_xbar_mux_001_src_valid),                                       //          .valid
		.src_data            (rsp_xbar_mux_001_src_data),                                        //          .data
		.src_channel         (rsp_xbar_mux_001_src_channel),                                     //          .channel
		.src_startofpacket   (rsp_xbar_mux_001_src_startofpacket),                               //          .startofpacket
		.src_endofpacket     (rsp_xbar_mux_001_src_endofpacket),                                 //          .endofpacket
		.sink0_ready         (crosser_003_out_ready),                                            //     sink0.ready
		.sink0_valid         (crosser_003_out_valid),                                            //          .valid
		.sink0_channel       (crosser_003_out_channel),                                          //          .channel
		.sink0_data          (crosser_003_out_data),                                             //          .data
		.sink0_startofpacket (crosser_003_out_startofpacket),                                    //          .startofpacket
		.sink0_endofpacket   (crosser_003_out_endofpacket)                                       //          .endofpacket
	);

	altera_avalon_st_handshake_clock_crosser #(
		.DATA_WIDTH          (234),
		.BITS_PER_SYMBOL     (234),
		.USE_PACKETS         (1),
		.USE_CHANNEL         (1),
		.CHANNEL_WIDTH       (2),
		.USE_ERROR           (0),
		.ERROR_WIDTH         (1),
		.VALID_SYNC_DEPTH    (2),
		.READY_SYNC_DEPTH    (2),
		.USE_OUTPUT_PIPELINE (0)
	) crosser (
		.in_clk            (hps_0_h2f_user0_clock_clk),                                        //        in_clk.clk
		.in_reset          (hps_0_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), //  in_clk_reset.reset
		.out_clk           (clock_bridge_0_out_clk_clk),                                       //       out_clk.clk
		.out_reset         (h2f_slave_0_reset_reset_bridge_in_reset_reset),                    // out_clk_reset.reset
		.in_ready          (cmd_xbar_demux_src0_ready),                                        //            in.ready
		.in_valid          (cmd_xbar_demux_src0_valid),                                        //              .valid
		.in_startofpacket  (cmd_xbar_demux_src0_startofpacket),                                //              .startofpacket
		.in_endofpacket    (cmd_xbar_demux_src0_endofpacket),                                  //              .endofpacket
		.in_channel        (cmd_xbar_demux_src0_channel),                                      //              .channel
		.in_data           (cmd_xbar_demux_src0_data),                                         //              .data
		.out_ready         (crosser_out_ready),                                                //           out.ready
		.out_valid         (crosser_out_valid),                                                //              .valid
		.out_startofpacket (crosser_out_startofpacket),                                        //              .startofpacket
		.out_endofpacket   (crosser_out_endofpacket),                                          //              .endofpacket
		.out_channel       (crosser_out_channel),                                              //              .channel
		.out_data          (crosser_out_data),                                                 //              .data
		.in_empty          (1'b0),                                                             //   (terminated)
		.in_error          (1'b0),                                                             //   (terminated)
		.out_empty         (),                                                                 //   (terminated)
		.out_error         ()                                                                  //   (terminated)
	);

	altera_avalon_st_handshake_clock_crosser #(
		.DATA_WIDTH          (234),
		.BITS_PER_SYMBOL     (234),
		.USE_PACKETS         (1),
		.USE_CHANNEL         (1),
		.CHANNEL_WIDTH       (2),
		.USE_ERROR           (0),
		.ERROR_WIDTH         (1),
		.VALID_SYNC_DEPTH    (2),
		.READY_SYNC_DEPTH    (2),
		.USE_OUTPUT_PIPELINE (0)
	) crosser_001 (
		.in_clk            (hps_0_h2f_user0_clock_clk),                                        //        in_clk.clk
		.in_reset          (hps_0_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), //  in_clk_reset.reset
		.out_clk           (clock_bridge_0_out_clk_clk),                                       //       out_clk.clk
		.out_reset         (h2f_slave_0_reset_reset_bridge_in_reset_reset),                    // out_clk_reset.reset
		.in_ready          (cmd_xbar_demux_001_src0_ready),                                    //            in.ready
		.in_valid          (cmd_xbar_demux_001_src0_valid),                                    //              .valid
		.in_startofpacket  (cmd_xbar_demux_001_src0_startofpacket),                            //              .startofpacket
		.in_endofpacket    (cmd_xbar_demux_001_src0_endofpacket),                              //              .endofpacket
		.in_channel        (cmd_xbar_demux_001_src0_channel),                                  //              .channel
		.in_data           (cmd_xbar_demux_001_src0_data),                                     //              .data
		.out_ready         (crosser_001_out_ready),                                            //           out.ready
		.out_valid         (crosser_001_out_valid),                                            //              .valid
		.out_startofpacket (crosser_001_out_startofpacket),                                    //              .startofpacket
		.out_endofpacket   (crosser_001_out_endofpacket),                                      //              .endofpacket
		.out_channel       (crosser_001_out_channel),                                          //              .channel
		.out_data          (crosser_001_out_data),                                             //              .data
		.in_empty          (1'b0),                                                             //   (terminated)
		.in_error          (1'b0),                                                             //   (terminated)
		.out_empty         (),                                                                 //   (terminated)
		.out_error         ()                                                                  //   (terminated)
	);

	altera_avalon_st_handshake_clock_crosser #(
		.DATA_WIDTH          (234),
		.BITS_PER_SYMBOL     (234),
		.USE_PACKETS         (1),
		.USE_CHANNEL         (1),
		.CHANNEL_WIDTH       (2),
		.USE_ERROR           (0),
		.ERROR_WIDTH         (1),
		.VALID_SYNC_DEPTH    (2),
		.READY_SYNC_DEPTH    (2),
		.USE_OUTPUT_PIPELINE (0)
	) crosser_002 (
		.in_clk            (clock_bridge_0_out_clk_clk),                                       //        in_clk.clk
		.in_reset          (h2f_slave_0_reset_reset_bridge_in_reset_reset),                    //  in_clk_reset.reset
		.out_clk           (hps_0_h2f_user0_clock_clk),                                        //       out_clk.clk
		.out_reset         (hps_0_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // out_clk_reset.reset
		.in_ready          (rsp_xbar_demux_src0_ready),                                        //            in.ready
		.in_valid          (rsp_xbar_demux_src0_valid),                                        //              .valid
		.in_startofpacket  (rsp_xbar_demux_src0_startofpacket),                                //              .startofpacket
		.in_endofpacket    (rsp_xbar_demux_src0_endofpacket),                                  //              .endofpacket
		.in_channel        (rsp_xbar_demux_src0_channel),                                      //              .channel
		.in_data           (rsp_xbar_demux_src0_data),                                         //              .data
		.out_ready         (crosser_002_out_ready),                                            //           out.ready
		.out_valid         (crosser_002_out_valid),                                            //              .valid
		.out_startofpacket (crosser_002_out_startofpacket),                                    //              .startofpacket
		.out_endofpacket   (crosser_002_out_endofpacket),                                      //              .endofpacket
		.out_channel       (crosser_002_out_channel),                                          //              .channel
		.out_data          (crosser_002_out_data),                                             //              .data
		.in_empty          (1'b0),                                                             //   (terminated)
		.in_error          (1'b0),                                                             //   (terminated)
		.out_empty         (),                                                                 //   (terminated)
		.out_error         ()                                                                  //   (terminated)
	);

	altera_avalon_st_handshake_clock_crosser #(
		.DATA_WIDTH          (234),
		.BITS_PER_SYMBOL     (234),
		.USE_PACKETS         (1),
		.USE_CHANNEL         (1),
		.CHANNEL_WIDTH       (2),
		.USE_ERROR           (0),
		.ERROR_WIDTH         (1),
		.VALID_SYNC_DEPTH    (2),
		.READY_SYNC_DEPTH    (2),
		.USE_OUTPUT_PIPELINE (0)
	) crosser_003 (
		.in_clk            (clock_bridge_0_out_clk_clk),                                       //        in_clk.clk
		.in_reset          (h2f_slave_0_reset_reset_bridge_in_reset_reset),                    //  in_clk_reset.reset
		.out_clk           (hps_0_h2f_user0_clock_clk),                                        //       out_clk.clk
		.out_reset         (hps_0_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // out_clk_reset.reset
		.in_ready          (rsp_xbar_demux_src1_ready),                                        //            in.ready
		.in_valid          (rsp_xbar_demux_src1_valid),                                        //              .valid
		.in_startofpacket  (rsp_xbar_demux_src1_startofpacket),                                //              .startofpacket
		.in_endofpacket    (rsp_xbar_demux_src1_endofpacket),                                  //              .endofpacket
		.in_channel        (rsp_xbar_demux_src1_channel),                                      //              .channel
		.in_data           (rsp_xbar_demux_src1_data),                                         //              .data
		.out_ready         (crosser_003_out_ready),                                            //           out.ready
		.out_valid         (crosser_003_out_valid),                                            //              .valid
		.out_startofpacket (crosser_003_out_startofpacket),                                    //              .startofpacket
		.out_endofpacket   (crosser_003_out_endofpacket),                                      //              .endofpacket
		.out_channel       (crosser_003_out_channel),                                          //              .channel
		.out_data          (crosser_003_out_data),                                             //              .data
		.in_empty          (1'b0),                                                             //   (terminated)
		.in_error          (1'b0),                                                             //   (terminated)
		.out_empty         (),                                                                 //   (terminated)
		.out_error         ()                                                                  //   (terminated)
	);

endmodule
